<a href="https://colab.research.google.com/github/SixEyesSaiyan/MS-DS/blob/main/python_crash_course.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python Crash Course

Part 1

In [ ]:
1 #Integer

1

In [ ]:
1.0 #Floating Point Number

1.0

In [ ]:
1 + 1 #Addition

2

In [ ]:
1 * 3 #Multiplication

3

In [ ]:
1 / 2.0 #Division

0.5

In [ ]:
2 ** 4 #Exponents

16

In [ ]:
2 + 3 * 5 + 5 #Order of Operations

22

In [ ]:
(2+3) * (5+5) #Parentheses

50

In [ ]:
4 % 2 #Modulus

0

In [ ]:
5 % 2

1

In [ ]:
8 % 2

0

In [ ]:
var = 2

In [ ]:
var

2

In [ ]:
x = 2
y = 3

In [ ]:
x + y

5

In [ ]:
x = x+x

In [ ]:
x

4

In [ ]:
x = x+x

In [ ]:
x

8

In [ ]:
12var = 12 #Cannot start with number

SyntaxError: invalid decimal literal (<ipython-input-23-541d0f0b8971>, line 1)

In [ ]:
$var = 12 #Cannot start with special character

SyntaxError: invalid syntax (<ipython-input-68-8fe73c76f2cf>, line 1)

In [ ]:
name_of_var = 12

In [ ]:
name_of_var

12

In [ ]:
# Strings COMMENT

In [ ]:
' single quote '

' single quote '

In [ ]:
"this is a string"

'this is a string'

In [ ]:
"I can't go"

"I can't go"

In [ ]:
x = 'hello'

In [ ]:
x

'hello'

In [ ]:
print(x)

hello


In [ ]:
num = 12
name = 'Sam'

In [ ]:
print('My number is {} and my name is {}'.format(num,name))

My number is 12 and my name is Sam


In [ ]:
print('My number is {one} and my name is {two}, more {one}'.format(one=num,two=name))

My number is 12 and my name is Sam, more 12


In [ ]:
s = 'hello'

In [ ]:
s[0]

'h'

In [ ]:
s[-1]

'o'

In [ ]:
s = 'abcdefghijk'

In [ ]:
s[0:] #Everything after index 0 (Slicing)

'abcdefghijk'

In [ ]:
s[:3] #Everything up to index 3 (Slicing)

'abc'

In [ ]:
s[3:6] #Everything from index 3 to 6 (Slicing)

'def'

In [ ]:
[1,2,3] #List

[1, 2, 3]

In [ ]:
['a','b','c']

['a', 'b', 'c']

In [ ]:
my_list = ['a','b','c']

In [ ]:
my_list.append('d')

In [ ]:
my_list

['a', 'b', 'c', 'd']

In [ ]:
my_list[0]

'a'

In [ ]:
my_list[1:3]

['b', 'c']

In [ ]:
my_list[0] = 'NEW'

In [ ]:
my_list

['NEW', 'b', 'c', 'd']

In [ ]:
nest = [1,2,[3,4]]

In [ ]:
nest

[1, 2, [3, 4]]

In [ ]:
nest[2]

[3, 4]

In [ ]:
nest[2][1]

4

In [ ]:
nest = [1,2,3,[4,5,['target']]]

In [ ]:
nest[3]

[4, 5, ['target']]

In [ ]:
nest[3][2]

['target']

In [ ]:
nest[3][2][0]

'target'

In [ ]:
print(nest[3][2][0])

target


Part 2

In [ ]:
d = {'key1':'value','key2':123} #Dictionaries

In [ ]:
d

{'key1': 'value', 'key2': 123}

In [ ]:
d['key1']

'value'

In [ ]:
d['key2']

123

In [ ]:
d = {'k1':[1,2,3]}

In [ ]:
d['k1']

[1, 2, 3]

In [ ]:
d['k1'][1]

2

In [ ]:
my_list = d['k1']

In [ ]:
my_list[0]

1

In [ ]:
d['k1'][0]

1

In [ ]:
d = {'k1':{'innerkey':[1,2,3]}} #Dictionaries within Dictionaries

In [ ]:
d['k1']['innerkey'][1]

2

In [ ]:
True #Boolean

True

In [ ]:
False #Boolean

False

In [ ]:
my_list = [1,2,3]

In [ ]:
my_list[0]

1

In [ ]:
t = (1,2,3) #Tuples

In [ ]:
t[0]

1

In [ ]:
my_list[0] = 'NEW'

In [ ]:
my_list

['NEW', 2, 3]

In [ ]:
t[0] = 'NEW' #Tuples are immutable

TypeError: 'tuple' object does not support item assignment

In [ ]:
{1,2,3} #Sets

{1, 2, 3}

In [ ]:
{1,1,1,2,2,2,3,3,3} #Sets only have unique elements

{1, 2, 3}

In [ ]:
set([1,1,1,2,2,2,3,3,3])

{1, 2, 3}

In [ ]:
s = {1,2,3}

In [ ]:
s.add(5)

In [ ]:
s

{1, 2, 3, 5}

In [ ]:
s.add(5) #Sets only have unique elements

In [ ]:
s

{1, 2, 3, 5}

In [ ]:
1 > 2 #Comparison Operators

False

In [ ]:
1 < 2

True

In [ ]:
1 >= 2

False

In [ ]:
1 <= 1

True

In [ ]:
1 == 1

True

In [ ]:
1 != 3

True

In [ ]:
'hi' == 'bye' #String Comparison

False

In [ ]:
'hi' != 'bye'

True

In [ ]:
1 < 2 and 2 < 3 #Logical Operators

True

In [ ]:
1 < 2 and 2 > 3

False

In [ ]:
(1 < 2) or (2 > 3) or (1 == 1)

True

In [ ]:
True and True #Boolean Operators

True

In [ ]:
True and False

False

In [ ]:
True or False

True

In [ ]:
if 1 < 2: #If Statements
    print('yep!')

yep!


In [ ]:
if True:
    x = 2 + 2

In [ ]:
x

4

In [ ]:
if 1 == 2:
    print('First')
else:
    print('Last')

Last


In [ ]:
if 1 != 2:
    print('First')
else:
    print('Last')

First


In [ ]:
if 1 == 2:
    print('First')
elif 3 == 3:
    print('Middle')
else:
    print('Last')

Middle


In [ ]:
if 1 == 2:
    print('First')
elif 4 == 4:
    print('Second')
elif 3 == 3:
    print('Middle')
else:
    print('Last')

Second


Part 3

In [ ]:
seq = [1,2,3,4,5]

In [ ]:
for num in seq: #For Loops
    print(num)

1
2
3
4
5


In [ ]:
for num in seq:
  print('hello')

hello
hello
hello
hello
hello


In [ ]:
i = 1

while i < 5: #While Loops
    print('i is: {}'.format(i))
    i = i+1

i is: 1
i is: 2
i is: 3
i is: 4


In [ ]:
for x in seq:
    print(x)

1
2
3
4
5


In [ ]:
range(0,5) #Range

range(0, 5)

In [ ]:
for x in range(0,5):
    print(x)

0
1
2
3
4


In [ ]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
x = [1,2,3,4]

In [ ]:
out = []

for num in x:
    out.append(num**2)

In [ ]:
print(out)

[1, 4, 9, 16]


In [ ]:
[num**2 for num in x] #List Comprehension

[1, 4, 9, 16]

In [ ]:
out = [num**2 for num in x]

In [ ]:
out

[1, 4, 9, 16]

In [ ]:
def my_func(param1): #Functions
    print(param1)

In [ ]:
my_func('hello')

hello


In [ ]:
def my_func(name):
    print('Hello ' + name)

In [ ]:
my_func('Sam')

Hello Sam


In [ ]:
def my_func(name='Default Name'):
    print('Hello ' + name)

In [ ]:
my_func()

Hello Default Name


In [ ]:
def square(num):
    """
    THIS IS A DOCSTRING.
    CAN GO MULTIPLE LINES.
    THIS FUNCTION SQUARES A NUMBER.
    """
    return num**2

In [ ]:
square(2)

4

In [ ]:
square #Shift + Tab to see docstring

<function __main__.square(num)>

Part 4

In [ ]:
def times2(var):return var*2

# lambda var: var*2 #Lambda Expression of above function

In [ ]:
times2(5)

10

In [ ]:
# map()

In [ ]:
seq = [1,2,3,4,5]

In [ ]:
map(times2,seq)

In [ ]:
list(map(times2,seq)) #Map

[2, 4, 6, 8, 10]

In [ ]:
list(map(lambda var: var*2,seq)) #Lambda Expression

[2, 4, 6, 8, 10]

In [ ]:
filter(lambda item: item%2 == 0,seq) #Filter

In [ ]:
list(filter(lambda item: item%2 == 0,seq))

[2, 4]

In [ ]:
s = 'hello my name is Sam'

In [ ]:
s.lower() #String Methods

'hello my name is sam'

In [ ]:
s.upper()

'HELLO MY NAME IS SAM'

In [ ]:
s.split() #Splits on all the white spaces

['hello', 'my', 'name', 'is', 'Sam']

In [ ]:
tweet = 'Go Sports! #Sports'

In [ ]:
tweet.split('#')

['Go Sports! ', 'Sports']

In [ ]:
tweet.split('#')[1]

'Sports'

In [ ]:
d = {'k1':1,'k2':2}

In [ ]:
d

{'k1': 1, 'k2': 2}

In [ ]:
d.keys() #Dictionary Methods

dict_keys(['k1', 'k2'])

In [ ]:
d.items()

dict_items([('k1', 1), ('k2', 2)])

In [ ]:
d.values()

dict_values([1, 2])

In [ ]:
lst = [1,2,3]

In [ ]:
lst.pop() #List Methods

3

In [ ]:
lst

[1, 2]

In [ ]:
lst = [1,2,3,4,5]

In [ ]:
item = lst.pop()

In [ ]:
lst

[1, 2, 3, 4]

In [ ]:
item

5

In [ ]:
first = lst.pop(0)

In [ ]:
lst

[2, 3, 4]

In [ ]:
first

1

In [ ]:
lst.append('new')

In [ ]:
lst

[2, 3, 4, 'new']

In [ ]:
'x' in [1,2,3] #In Operator

False

In [ ]:
'x' in ['x','y','z']

True

In [ ]:
x = [(1,2),(3,4),(5,6)] #List of tuples

In [ ]:
for item in x: #Tuple Unpacking
    print(item)

(1, 2)
(3, 4)
(5, 6)


In [ ]:
for (a,b) in x:
    print(a)

1
3
5


In [ ]:
for (a,b) in x:
    print(b)

2
4
6


In [ ]:
for a,b in x:
    print(a)

1
3
5


Exercises

In [ ]:
7 ** 4

2401

In [ ]:
s = 'Hi there Sam!'

s.split()

['Hi', 'there', 'Sam!']

In [ ]:
planet = "Earth"
diameter = 12742

print("The diameter of {} is {} kilometers.".format(planet,diameter))

The diameter of Earth is 12742 kilometers.


In [ ]:
lst = [1,2,[3,4],[5,[100,200,['hello']],23,11],1,7]

lst[3][1][2][0]

'hello'

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [ ]:
def domainGet(email): return email.split('@')[1]

In [ ]:
domainGet('john.catron@example-pet-store.com')

'example-pet-store.com'

In [ ]:
'dog' in 'Is there a dog here'

True

In [ ]:
def countDog(st):
    count = 0
    for word in st.lower().split():
        if word == 'dog':
            count += 1
    return count

In [ ]:
countDog('This dog runs faster than the other dog dude!')

2

In [ ]:
seq = ['soup','dog','salad','cat','great']

list(filter(lambda word: word[0]=='s',seq))

['soup', 'salad']

In [ ]:
def caught_speeding(speed, is_birthday):
    if is_birthday:
        speeding = speed - 5
    else:
        speeding = speed

    if speeding > 80:
        return 'Big Ticket'
    elif speeding > 60:
        return 'Small Ticket'
    else:
        return 'No Ticket'

In [ ]:
caught_speeding(81,True)

'Small Ticket'

In [ ]:
caught_speeding(81,False)

'Big Ticket'

# Numpy

In [2]:
import numpy as np #Numpy

In [5]:
arr = np.array([1,2,3]) # Creating a rank 1 Array

print("Array with Rank 1: \n",arr)

arr = np.array([[1, 2, 3],
                [4, 5, 6]]) # Creating a rank 2 Array
print("Array with Rank 2: \n", arr)


arr = np.array((1, 3, 2)) # Creating an array from tuple
print("\nArray created using "
      "passed tuple:\n", arr)

Array with Rank 1: 
 [1 2 3]
Array with Rank 2: 
 [[1 2 3]
 [4 5 6]]

Array created using passed tuple:
 [1 3 2]


In [9]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]]) # Initial Array
print("Initial Array: ")
print(arr)


sliced_arr = arr[:2, ::2] # Printing a range of Array with the use of slicing method
print ("Array with first 2 rows and"
    " alternate columns(0 and 2):\n", sliced_arr)


Index_arr = arr[[1, 1, 0, 3],
                [3, 2, 1, 0]] # Printing elements at specific Indices
print ("\nElements at indices (1, 3), "
    "(1, 2), (0, 1), (3, 0):\n", Index_arr)

Initial Array: 
[[-1.   2.   0.   4. ]
 [ 4.  -0.5  6.   0. ]
 [ 2.6  0.   7.   8. ]
 [ 3.  -7.   4.   2. ]]
Array with first 2 rows and alternate columns(0 and 2):
 [[-1.  0.]
 [ 4.  6.]]

Elements at indices (1, 3), (1, 2), (0, 1), (3, 0):
 [0. 6. 2. 3.]
